### ISSUE TITLE
ClassCastException after changing theme to dark

### ISSUE THREAD

**Issue by devslava** [michael-rapp/AndroidPreferenceActivity#14]
I am experiencing ClassCastException in sample app after setting dark theme in Appearance. It happens when I click any of SHOW buttons at the main screen.
Android 4.4.2, tablet layout.
[stacktrace.txt](https://github.com/michael-rapp/AndroidPreferenceActivity/files/175822/stacktrace.txt)

**Comment by michael-rapp** [comment]
Fixed in version 4.1.0.
