### ISSUE TITLE
UI issue with Tablet in Portrait mode.

### ISSUE THREAD

**Issue by ItsCalebJones** [michael-rapp/AndroidPreferenceActivity#17]
[7inch Tablet](http://imgur.com/a/rHv59)

Also, note the title is still black text? =/

**Comment by michael-rapp** [comment]
What kind of device/emulator is this? What's its resolution (in pixels)?

**Comment by michael-rapp** [comment]
Do you expect it to look like on a smartphone (no sidebar)? If a sidebar should be shown, I have to reduce its width resulting in less horizontal space for the navigation items (at least in portrait mode).

**Comment by ItsCalebJones** [comment]
It's a Nexus 7" 1200 x 1920, I think most 7" tablets would look similar. I'm not sure what looks best, I would guess no sidebar would look good.

**Comment by michael-rapp** [comment]
That would also be my preferred solution.  A fix will come soon.

**Comment by michael-rapp** [comment]
I set up an emulator and the layout looks the same, but the toolbar text color looks proper. Maybe you can post your `styles.xml`?

**Comment by michael-rapp** [comment]
Layout fixed in version 4.2.6.

**Comment by ItsCalebJones** [comment]
I figured out the text issue, I forgot to parent from your theme. 0_o
