### ISSUE TITLE
Click's not registering on various Android versions.

### ISSUE THREAD

**Issue by ItsCalebJones** [michael-rapp/AndroidPreferenceActivity#19]
Unfortunately this is a really complex issue that I've spent the better half of a day troubleshooting. In the most simple explanation on various Android versions some preferences are not registering clicks.

On Android 6 and above, no SwitchPrefrerences or CheckboxPrefrerences are registering clicks.

On ~API 19 and below no CheckboxPrefrerences are registering clicks.

However, when I add my preference and fragment to your example project things are working perfectly.

I can attach an APK if you'd like to test it. You can view my [code here](https://github.com/caman9119/SpaceLaunchNow/tree/calendar_sync/mobile/src/main/java/me/calebjones/spacelaunchnow/settings) and a quick [demo of the issue](https://www.youtube.com/watch?v=bQQUEDmTlTc&feature=youtu.be).

**Comment by michael-rapp** [comment]
Okay, this is super awkward. I've never encountered an issue like this. But if it does only happen in your app, but not in the library's example app, this is an indicator that there is a problem with your code, right? 

I would try to create a minimal working example by step-by-step removing all code fragments, which are not absolutely necessary (e.g. listeners). As soon as the issue goes away, you know what's causing the problem.

**Comment by ItsCalebJones** [comment]
I would agree if I hadn't already done that. =/ Which is why I tried using my fragment and preference xml in the example project. Even the style of the switches and the like are different. This is really bizarre. My next test is going to a clean project with no 3rd party libraries, that's the only thing left in my mind that can be affecting this.

**Comment by michael-rapp** [comment]
Yes, maybe it is conflicting with a 3rd party library. I saw that you're using a lot of them.

**Comment by ItsCalebJones** [comment]
I found the offender, my previous implementation of preferences relied on 'com.android.support:preference-v7'. Removing this fixed the issues I was having, might want to add that to the README.

**Comment by michael-rapp** [comment]
I'm glad to hear that it works now. I've added this information to the README.

**Comment by markusressel** [comment]
Just to update this:

This issue also arises if you include ```com.android.support:preference-v14``` in your project next to this library. So if you want to use this library in production you first have to fully replace the default preference system.

**Comment by michael-rapp** [comment]
@markusressel This library requires API level 14 at least (because of the AppCompat support library). So there is no need to use `com.android.support:preference-v7` or `com.android.support:preference-v14` anyway. Or do I miss something?

**Comment by markusressel** [comment]
@michael-rapp I guess you're right. I just wanted to mention the ```v14``` version here too for documentation purpose as I had the same problem but was **not** using ```v7```.

**Comment by michael-rapp** [comment]
@markusressel Thank you for pointing this out. I will add a notice to the readme.
