### ISSUE TITLE
Can I display a back button at the base fragment of the activity?

### ISSUE THREAD

**Issue by iBlueDust** [michael-rapp/AndroidPreferenceActivity#29]
My preference activity is called from a main activity. However, the preference activity's appbar does not show a back button to trigger `onBackPressed()`. 

How do I display a back button at the base/first fragment?

PS: The activity is already set as child of the main activity. Really great library btw.

**Comment by michael-rapp** [comment]
Just add the following to your activity's `onCreate`-method:

```java
@Override
protected void onCreate(final Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    ActionBar actionBar = getSupportActionBar();
    actionBar.setDisplayHomeAsUpEnabled(true);
}
```

**Comment by iBlueDust** [comment]
Thanks a lot!

btw adding
```
@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if(item.getItemId() == android.R.id.home) {
            onBackPressed();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
```
will help to display the right animation.
